# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicalskills', models.CharField(max_length=500)),
                ('projects', models.CharField(max_length=500)),
                ('achievements', models.CharField(max_length=100)),
                ('workshops', models.CharField(max_length=500)),
                ('internships', models.CharField(max_length=300)),
            ],
        ),
    ]
