# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeinfo',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='resumeinfo',
            name='internships',
        ),
        migrations.RemoveField(
            model_name='resumeinfo',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resumeinfo',
            name='technicalskills',
        ),
        migrations.RemoveField(
            model_name='resumeinfo',
            name='workshops',
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Achievements',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Add',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Current_city',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Email',
            field=models.EmailField(default='SOME STRING', max_length=25),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Full_name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Github',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Graduation_percent',
            field=models.FloatField(default=75.6),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Internships',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Job_expr',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Projects',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Technicalskills',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Tenth_percent',
            field=models.FloatField(default=92.3),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Twelth_percent',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='resumeinfo',
            name='Workshops',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
